### ISSUE TITLE
getParent这个没有定义哈

### ISSUE THREAD

**Issue by d1studio** [Comos/qpm#1]
Notice: Undefined variable: msq in /Users/chengtao/opencode/php/qpm/_examples/qpm_daemon.php on line 44

localhost:qpm chengtao$ find . -name "*.php" |xargs grep "getParent"
./_examples/qpm_daemon.php: $msg = sprintf("PID: %d\tPPID:%d\n", Process::current()->getPid(), Process::current()->getParent()->getPid());
localhost:qpm chengtao$ pwd
/Users/chengtao/opencode/php/qpm

**Comment by bigbigant** [comment]
Thanks
I'll fix it as soon as possible.

**Comment by bigbigant** [comment]
Added the method Process::getParent().
