### ISSUE TITLE
判断类实现了哪些借口好像不能用这个get_parent_class，应该用ReflectionClass吧？

### ISSUE THREAD

**Issue by d1studio** [Comos/qpm#2]
/qpm/library/qpm/supervisor/Config.php  line: 85行
        if (isset($config['runnableClass'])) {
            $clazz = $config['runnableClass'];
            if (!is_subclass_of($clazz, '\qpm\process\Runnable')) {
                throw new \InvalidArgumentException('runnableClass must be an implemention of \qpm\process\Runnable');
            }
            $this->_factoryMethod = function() use($clazz) {
                return array((new $clazz()), 'run');
            };
            return;
        }
is_subclass_of 这个函数好像不能获得这个类实现的接口列表

class Test extends \qpm\supervisor\Supervisor{}
class QWorker implements \qpm\process\Runnable{
    public function run(){
        while(true) {
            echo "+++run2,pid:".posix_getpid()."\n";
            require_once '../lib/RabbitMq.class.php';
            RabbitMq::getQueue()->consume(function($envelope, $queue) {
                $msg = $envelope->getBody();
                echo $msg."\n"; //处理消息
                $queue->ack($envelope->getDeliveryTag()); //手动发送ACK应答
            });
        }
        return 0;
    }
}
echo "Out:".get_parent_class('Test');echo "\n";
echo "Out:".get_parent_class('QWorker');echo "\n";
print_r ((new ReflectionClass("QWorker"))->getInterfaceNames());echo "\n";
exit;

－－－－－－－－－－－－－－－－－－
localhost:collect chengtao$ /usr/local/php/bin/php main.php 
Out:qpm\supervisor\Supervisor
Out:
Array
(
    [0] => qpm\process\Runnable
)

localhost:collect chengtao$

**Comment by bigbigant** [comment]
这里用is_subclass_of 并不需要获取接口列表，只是检测下是否实现了某个接口, 返回boolean。

<?php
interface I1 {
        public function foo();
}

interface I2 {
        public function bar();
}

class C implements I1,I2{
        public function foo() {}
        public function bar() {}
}

echo "\n C I1:".is_subclass_of('C', 'I1');// 1
echo "\n C I2:".is_subclass_of('C', 'I2');// 1
echo "\n C ArrayAccess:".is_subclass_of('C', 'ArrayAccess');// nothing

**Comment by d1studio** [comment]
我理解错了。。。。。Thanks～
