### ISSUE TITLE
OSX php5.5 timeout not work

### ISSUE THREAD

**Issue by 13leaf** [Comos/qpm#22]
OSX10.9.5 php5.5.26
php examples/handle_timeout_gentlely.php

**Comment by 13leaf** [comment]
仔细看了下。timeout应该是启作用了，例子没跑通是因为没有执行SIGTERM的回调通知。在ubuntu上是正常的

**Comment by bigbigant** [comment]
确实没有在osx php5.5测试过，这个版本我这边一直编译报错...
SIGTERM不响应理论上再等待一个超时周期后就执行SIGKILL了

**Comment by 13leaf** [comment]
不知为何，我这边SIG_TERM不能杀掉php，也不会触发回调钩子。也许是系统和php实现差异吧
