### ISSUE TITLE
添加到 https://packagist.org/

### ISSUE THREAD

**Issue by d1studio** [Comos/qpm#8]
＃ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package comos/qpm could not be found in any version, there may be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read http://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

**Comment by bigbigant** [comment]
Composer配置 @chengtao1633 你要不整体review一下吧。
另外你操作下添加packagist的事情如何？

目前需要强行指定仓库URL，配置的例子如下。

{
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/Comos/qpm.git"
        }
    ],
    "require": {
        "monolog/monolog": "1.0.*",
        "Comos/qpm":"0.2.1"
    }
}
